
name: Pionex Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

      - name: Télécharger le scanner
        uses: actions/checkout@v4

      - name: Lancer le scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TEST_MODE: "1"
        run: python scanner.py
